import type {
  AllData,
} from "./types";

export const demoData: AllData = {
  config: {
    site_title: "Boon | Future Scientist & Developer",
    brand: "BOON.DEV",
    tagline:
      "Using Python & Code to solve real-world problems.",
    footer_text: "Open to collaborations and ambitious projects.",
    copyright: "© 2026 APIWISH ANUTARAVANICHKUL.",
    socials: [
      { type: "email", label: "Email", url: "mailto:apiwishboon@gmail.com", icon: "fa-envelope" },
      { type: "github", label: "GitHub", url: "https://github.com/apiwishboon-spec", icon: "fa-github" },
      { type: "phone", label: "Phone", url: "tel:0933372907", icon: "fa-phone" },
      { type: "discord", label: "Discord", url: "https://discord.com/users/boon06409", icon: "fa-discord" },
    ],
    about: "I love solving complex problems, understanding human behavior, and turning ideas into code.",
    contact_heading: "Let's Build Something",
    contact_subtext: "Open to collaborations and ambitious projects.",
  },
  nav: [
    { id: "n1", label: "Home", href: "/", sort_order: 0, enabled: true },
    { id: "n2", label: "About", href: "/about", sort_order: 1, enabled: true },
    { id: "n3", label: "Projects", href: "/projects", sort_order: 2, enabled: true },
    { id: "n4", label: "Honors", href: "/honors", sort_order: 3, enabled: true },
    { id: "n5", label: "Blog", href: "/blog", sort_order: 4, enabled: true },
    { id: "n6", label: "Resources", href: "/resources", sort_order: 5, enabled: true },
    { id: "n7", label: "Uptime", href: "/uptime/", sort_order: 6, enabled: true },
  ],
  projects: [
    {
      id: "p1",
      slug: "cortexmail",
      title: "CortexMail",
      tagline: "AI-powered email assistant",
      description:
        "AI-powered email assistant that reads inboxes and drafts intelligent replies.",
      cover_url: "/cortexmail.png",
      tags: ["AI", "Assistant"],
      tech: ["Python", "AI"],
      live_url: "",
      github_url: "https://github.com/apiwishboon-spec",
      body: "AI-powered email assistant that reads inboxes and drafts intelligent replies. Built to streamline daily email workflows.",
      featured: true,
      sort_order: 0,
    },
    {
      id: "p2",
      slug: "synapsemail",
      title: "SynapseMail",
      tagline: "macOS email automation",
      description:
        "A specialized macOS app for local inbox automation and High-frequency IMAP monitoring.",
      cover_url: "/SynapseMail.png",
      tags: ["Automation", "macOS"],
      tech: ["Automation", "macOS"],
      live_url: "",
      github_url: "https://github.com/apiwishboon-spec",
      body: "A specialized macOS app for local inbox automation and High-frequency IMAP monitoring.",
      featured: true,
      sort_order: 1,
    },
  ],
  posts: [
    {
      id: "b1",
      slug: "moving-up-to-m2",
      title: "Moving Up to M.2",
      date: "2026-05-09",
      excerpt: "I am moving up to M.2 at my school, and I am really excited for the new year ahead.",
      body: "I am moving up to M.2 at my school, and I am really excited about it. It feels amazing to start a new school year, meet new teachers, learn new things, and take on new challenges. This new chapter brings fresh opportunities to learn advanced topics, participate in competitions, and make new friends.",
      image_url: "/profile_me.jpg",
      published: true,
      tags: ["school", "SK"],
    },
    {
      id: "b2",
      slug: "launching-the-new-portfolio",
      title: "Launching the New Portfolio",
      date: "2026-01-01",
      excerpt: "I redesigned boon.is-a.dev to feel cleaner, faster, and easier to navigate.",
      body: "I redesigned boon.is-a.dev to feel cleaner, faster, and easier to navigate. This release focuses on visual polish and better page flow, with a responsive layout that works great on all devices.",
      image_url: "/icon.png",
      published: true,
      tags: ["portfolio", "design"],
    },
    {
      id: "b3",
      slug: "building-an-uptime-dashboard",
      title: "Building an Uptime Dashboard",
      date: "2026-05-09",
      excerpt: "Added a simple monitoring page for site and service health.",
      body: "I built an uptime dashboard to monitor the health and availability of my websites and services. It checks key endpoints every minute and provides real-time status updates.",
      image_url: "/voyage.png",
      published: true,
      tags: ["uptime", "javascript"],
    },
  ],
  honors: [
    {
      id: "h1",
      title: "นักเรียนดีเด่นด้านคุณธรรม",
      description: "ความเสียสละ",
      image_url: "/S__24813602.jpg",
      alt: "นักเรียนดีเด่นด้านคุณธรรม",
      badge_class: "bg-success text-white",
      badge_icon: "fa-solid fa-heart",
      badge_label: "Outstanding",
      badge_title: "Outstanding Student in Morality (Sacrifice)",
      pin_color: "bg-warning",
      rotation: "1deg",
      sort_order: 0,
    },
    {
      id: "h2",
      title: "ASMOPSS Thailand 2023",
      description: "English Primary - Bronze Medalist",
      image_url: "/eng-2023-bronze.jpg",
      alt: "ASMOPSS Thailand 2023 Bronze Medalist Certificate",
      badge_class: "bg-secondary text-white",
      badge_icon: "fa-solid fa-medal",
      badge_label: "Bronze Medalist",
      badge_title:
        "Asian Science and Mathematics Olympiad for Primary and Secondary Schools",
      pin_color: "bg-danger",
      rotation: "-2deg",
      sort_order: 1,
    },
  ],
  resources: [
    {
      id: "r1",
      category: "Crafting",
      title: "Small Book Template",
      description: "Printable template for creating small handmade books",
      file_url: "/downloads/file resorce/small_book.png",
      preview_url: "/downloads/file resorce/small_book.png",
      file_type: "PNG",
      file_size: "1.2 MB",
      protected: false,
      sort_order: 0,
    },
    {
      id: "r2",
      category: "Science",
      title: "Science Guide",
      description: "Comprehensive science experiments and research methods",
      file_url: "",
      file_type: "PDF",
      file_size: "Coming Soon",
      protected: false,
      sort_order: 0,
    },
    {
      id: "r3",
      category: "Other",
      title: "I21202 Bullying Research",
      description: "Independent study on bullying in Grade 7 at Suankularb Wittayalai School",
      file_url: "/downloads/file resorce/bullying_research.pdf",
      preview_url: "https://i.postimg.cc/3wC1DCpk/Screenshot-2569-03-01-at-21-46-32.png",
      file_type: "PDF",
      file_size: "2.8 MB",
      protected: false,
      sort_order: 0,
    },
  ],
  timeline: [
    {
      id: "t1",
      period_label: "Grade 1 - 6",
      title: "Bangkok Christian College",
      description: "Built my foundation in coding and mathematics.",
      icon: "fa-shuttle-space",
      is_current: false,
      sort_order: 0,
    },
    {
      id: "t2",
      period_label: "Grade 7 (Current)",
      title: "Suankularb Wittayalai School",
      description: "Expanding my horizons in computer science and robotics.",
      icon: "fa-user-astronaut",
      is_current: true,
      sort_order: 1,
    },
  ],
  skills: [
    { id: "s1", label: "Python (Advanced)", sort_order: 0 },
    { id: "s2", label: "Data Science", sort_order: 1 },
    { id: "s3", label: "Algorithms", sort_order: 2 },
    { id: "s4", label: "Psychology", sort_order: 3 },
    { id: "s5", label: "Astronomy", sort_order: 4 },
    { id: "s6", label: "HTML", sort_order: 5 },
    { id: "s7", label: "Problem Solving", sort_order: 6 },
    { id: "s8", label: "Science", sort_order: 7 },
    { id: "s9", label: "Research", sort_order: 8 },
    { id: "s10", label: "Engineering", sort_order: 9 },
  ],
};
